# This is a basic workflow to generate build on latest master
name: "pre-release"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
  workflow_dispatch:
    inputs:
      comment:
        description: 'Add comment for manual workflow execution.'
        required: false
        default: 'Manual execution of Github workflow.'

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "checking secrets"
        shell: bash
        run: |
          echo "${{ secrets.SPLUNKBASE_USERNAME }} - ${{ secrets.SPLUNKBASE_PASSWORD }}"
          echo "${{secrets.splunkbase_username}} - ${{secrets.splunkbase_passsword}}"

      - uses: VatsalJagani/Splunk-App-Inspect-Check-Github-Action@test25
        env:
          env_app_dir: "lansweeper_app_for_splunk"
          env_app_build_name: "app"
          env_splunkbase_username: "${{ secrets.splunkbase_username }}"
          env_splunkbase_password: "${{ secrets.splunkbase_password }}"
        with:
          app_dir: "lansweeper_app_for_splunk"
          app_build_name: "app"
          splunkbase_username: "${{ secrets.SPLUNKBASE_USERNAME }}"
          splunkbase_password: "${{ secrets.SPLUNKBASE_PASSWORD }}"
        

      - uses: VatsalJagani/Splunk-App-Inspect-Check-Github-Action@test25
        env:
          env_app_dir: "TA-lansweeper-add-on-for-splunk"
          env_app_build_name: "ta"
          env_splunkbase_username: "${{ secrets.splunkbase_username }}"
          env_splunkbase_password: "${{ secrets.splunkbase_password }}"
        with:
          app_dir: "TA-lansweeper-add-on-for-splunk"
          app_build_name: "ta"
          splunkbase_username: "${{ secrets.splunkbase_username }}"
          splunkbase_password: "${{ secrets.splunkbase_password }}"
        
