# This is a basic workflow to generate build
name: "pre-release"

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'

  workflow_dispatch:

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: VatsalJagani/splunk-app-action@v4.1
        with:
          app_dir: "lansweeper_app_for_splunk"
          to_make_permission_changes: true
          splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
          splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}
          app_utilities: "whats_in_the_app"
          my_github_token: ${{ secrets.MY_GITHUB_TOKEN }}

      - uses: VatsalJagani/splunk-app-action@v4.1
        with:
          app_dir: "TA-lansweeper-add-on-for-splunk"
          to_make_permission_changes: true
          splunkbase_username: ${{ secrets.SPLUNKBASE_USERNAME }}
          splunkbase_password: ${{ secrets.SPLUNKBASE_PASSWORD }}
          app_utilities: "whats_in_the_app, logger, splunk_python_sdk"
          my_github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          logger_log_files_prefix: "ta_lansweeper"
          logger_sourcetype: "lansweeper-ta:logs"
          splunk_python_sdk_install_path: "lib"
